language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
php:
  - '7.0'
  - '7.1'
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install: composer install --no-interaction --optimize-autoloader --prefer-dist
before_script:
  - ./bin/test-tools get-html --rate 3
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 src/
