language: php
branches:
  only:
    - master
php:
  - '7.0'
  - '7.1'
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install: composer install --no-interaction --optimize-autoloader --prefer-dist
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 src/
